[tox]
envlist = py39, py310, py311, py312
skip_missing_interpreters = true

[testenv]
deps =
    .[dev]           # install your package with dev dependencies from pyproject.toml
commands =
    pytest --cov-fail-under=1  # fail if coverage is < 1%

[gh-actions]
python =
    3.9: py39
    3.10: py310
    3.11: py311
    3.12: py312
